### ISSUE TITLE
NvimError: Vim(nmap):E227:

### ISSUE THREAD

**Issue by gHashTag** [mfulz/cscope.nvim#3]
How to solve this error? After` CScopeStart`

```
error caught in async handler '/Users/xyz/.config/nvim/plugged/cscope.nvim/rplugin/python/nvim-cscope.py:command:CScopeMapKeys ([], [8, 8])'
Traceback (most recent call last):
  File "/Users/xyz/.config/nvim/plugged/cscope.nvim/rplugin/python/nvim-cscope.py", line 116, in cscope_map_keys_handler
    'nmap <unique> <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR>')
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 218, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
NvimError: Vim(nmap):E227: Уже есть привязка для ^\s
```

**Comment by mfulz** [comment]
Do you have a valid cscope.cfg file inside your project dir?

**Comment by gHashTag** [comment]
Yes
![2017-09-25 1 06 07](https://user-images.githubusercontent.com/6774813/30787281-c4de7902-a18d-11e7-9074-3e0aea2e66ab.png)

**Comment by mfulz** [comment]
Could you translate this message please for me? NvimError: Vim(nmap):E227: Уже есть привязка для ^\s

**Comment by gHashTag** [comment]
There is already a binding for

**Comment by mfulz** [comment]
Thanks, will check the next days where the issue could be.

**Comment by gHashTag** [comment]
Thanks, wait

**Comment by mfulz** [comment]
I could reproduce the issue, when calling CScopeStart multiple times in the same session. Didn't check if the mapping was already done. Could you please update to the latest commit and give feedback?

**Comment by gHashTag** [comment]
`no connections to cscope`


![bug mov](https://user-images.githubusercontent.com/6774813/30787551-eee6b43e-a193-11e7-9c15-935301abdf2f.gif)

**Comment by mfulz** [comment]
you've set the path to the cscope.nvim file. You need to configure the path to a folder.
Could you try to set "path = ~/AwesomeProject" and give feedback?
I've implemented a check for path being a folder in the last commit.

**Comment by gHashTag** [comment]
Connection is. Thank you
True, I now have three files. Is this right or what do I not need?
![2017-09-28 23 14 53](https://user-images.githubusercontent.com/6774813/30988455-ff256c70-a4a2-11e7-9d26-c6e3ba0601dd.png)

cscope.cfg
```# Project name will be created as subdir under cscope directory
name = AwesomeProject 

# Project path. The path to the project root.
# Where find will start searching the files.
path = ~/AwesomeProject

# file patterns to scan
files = *.js
```

cscope.nvim

```# Project name will be created as subdir under cscope directory
name = AwesomeProject 

# Project path. The path to the project root.
# Where find will start searching the files.
path = ~/AwesomeProject

# file patterns to scan
files = *.js
```

and I create cscope.out
This is correct?

**Comment by mfulz** [comment]
You just need the .cfg file. nothing else. The cscope.nvim is not needed (perhaps you misunderstood the docs here - my project dir for this was cscope.nvim).
The cscope.out is generated by the cscope.nvim plugin during start (with default config inside ~/.csope/{project_name}/). This behavior is configurable with the option "g:cscope_dir" in the normal nvim init file.
I hope I could help you to clarify your questions :)

**Comment by gHashTag** [comment]
Thanks

**Comment by mfulz** [comment]
You're welcome
